### ISSUE TITLE
Assignment statements causing exception

### ISSUE THREAD

**Issue by MadBomber** [janlelis/fancy_irb#14]
This is strange ... I'm working on venus a 2011 MacMini running MacOS 10.13.6  It has no Xcode installed.

```plaintext
15:50:03 3.2.2  venus:~ $ irb
irb(main):001> x = 1
/Users/dewayne/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fancy_irb-2.1.0/lib/fancy_irb/irb_ext.rb:3:in `output_value': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/dewayne/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fancy_irb-2.1.0/lib/fancy_irb/irb_ext.rb:9:in `signal_status'
	from /Users/dewayne/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.8.3/exe/irb:9:in `<top (required)>'
	from /Users/dewayne/.rbenv/versions/3.2.2/bin/irb:25:in `load'
	from /Users/dewayne/.rbenv/versions/3.2.2/bin/irb:25:in `<main>'
irb(main):002> exit
15:50:50 3.2.2  venus:~ $ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin17]
15:50:57 3.2.2  venus:~ $ irb --version
irb 1.8.3 (2023-10-14)
15:51:03 3.2.2  venus:~ $ gem list fancy_irb

*** LOCAL GEMS ***

fancy_irb (2.1.0)
15:51:12 3.2.2  venus:~ $
```

**Comment by MadBomber** [comment]
I was hoping this was just a problem on venus.  I went to a newer iMac running the latest OS, same Ruby, irb, fancy_irb versions and got the same exception.

**Comment by MadBomber** [comment]
I'm not convinced this is a problem in fancy_irb.   I downgraded to version 2.0.0 and then to  v1.4.3 of fancy_irb.  On those down grades I get this exception when irb is attempting to start up with that barebones .irbrc file:

NameError: undefined method `prompt' for class `IRB::Irb'

**Comment by MadBomber** [comment]
Final piece of troubleshoot today.  I commented out everything in the simple .irbrc file and irb loads and does its stuff without an problems.

**Comment by lain0** [comment]
Got the same problem, with both ruby 3.2.2 and 3.1.2, even with empty ~/.irbc file
```ruby
3.2.2 :002 > x = 1
/Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.1.0/lib/fancy_irb/irb_ext.rb:3:in `output_value': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.1.0/lib/fancy_irb/irb_ext.rb:9:in `signal_status'
	from /Users/serj/.rvm/gems/ruby-3.2.2/gems/irb-1.8.3/exe/irb:9:in `<top (required)>'
	from /Users/serj/.rvm/gems/ruby-3.2.2/bin/irb:25:in `load'
	from /Users/serj/.rvm/gems/ruby-3.2.2/bin/irb:25:in `<main>'
	from /Users/serj/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
	from /Users/serj/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'
3.2.2 :003 > FancyIrb::VERSION  #=> "2.1.0"
3.2.2 :004 > IRB::VERSION #=> "1.8.3"
3.2.2 :005 > RUBY_VERSION #=> "3.2.2"
```
```sh
ruby -v                                                             
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
```

**Comment by MadBomber** [comment]
Thank you for the fix.  My IRB is back online it all its Fancy glory!
