### ISSUE TITLE
NoMethodError: undefined method `[]' for FancyIrb:Module

### ISSUE THREAD

**Issue by mdesantis** [janlelis/fancy_irb#9]
Hello!

On Ruby 2.2.2 I get this error:

```
$ irb
Welcome to IRB. You are using ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]. Have fun ;)
>> "ciao"
NoMethodError: undefined method `[]' for FancyIrb:Module
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/irb-benchmark-0.1.2/lib/irb_benchmark.rb:12:in `print'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/irb-benchmark-0.1.2/lib/irb_benchmark/irb_ext.rb:11:in `evaluate'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fancy_irb-1.0.0/lib/fancy_irb/irb_ext.rb:31:in `evaluate'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fancy_irb-1.0.0/lib/fancy_irb/irb_ext.rb:19:in `signal_status'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:395:in `block in start'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:394:in `catch'
  from /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:394:in `start'
  from /home/user/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'Maybe IRB bug!
```
This is my .irbrc:

```ruby
begin
  require 'irbtools/configure'
  require 'irb-benchmark'
  require 'bond'

  Irbtools.remove_library 'boson/console' if RUBY_VERSION >= '2.2.0'
  Irbtools.start
  Bond.start
rescue LoadError
end
```

**Comment by mdesantis** [comment]
I verified it's a conflict with `irb-benchmark`, I'll update it ;-)
